name: Continuous integration

on:
  push:
    paths:
      - "**.rs"
      - "**Cargo.toml"
  pull_request:
    branches: [main]
    paths:
      - "**.rs"
      - "**Cargo.toml"
env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
      - uses: dtolnay/rust-toolchain@stable
        with:
          profile: minimal
          toolchain: stable
          components: clippy
      - name: Run clippy
        run: cargo clippy

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v1.3.0

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test

