name: Docker unstable release

on:
  push:
    branches:
      - main

jobs:
  server:
    name: Build server image
    runs-on: ubuntu-latest

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Get commit hash
        id: sha
        run: echo "::set-output name=sha::${GITHUB_SHA::7}"

      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.5.1

      # TODO: consider publishing to Docker Hub too
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1.10.0
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build images and push
        uses: docker/build-push-action@v2.6.1
        with:
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64, linux/arm64
          tags: |
            ghcr.io/itzbobocz/veteshnik:unstable
            ghcr.io/itzbobocz/veteshnik:unstable.${{ steps.date.outputs.date }}.${{ steps.sha.outputs.sha }}
